export const langConstant = {
  en: {
    play: "Play",
    moreInfo: "More Info",
    nowPlaying: "Now Playing",
    popular: "Popular",
    topRated: "Top Rated",
    upcoming: "Upcoming",
    gptSearch: "GPT Search",
    searchLabel: "Search",
    searchPlaceHolder: "What do you want to watch today?",
    homePageLabel: "Home Page",
    signInLabel: "Sign In",
    signUpLabel: "Sign Up",
    newUser: "New to Netflix?",
    exisitingUser: "Already a user",
    signUpNow: "Sign up now",
    namePlaceholder: "Name",
    emailPlaceholder: "Email",
    passwordPlaceholder: "Password",
    signOutLabel: "Sign Out",
  },
  hindi: {
    play: "चलाएं",
    moreInfo: "और जानकारी",
    nowPlaying: "अभी फिल्में चल रही हैं",
    popular: "लोकप्रिय",
    topRated: "टॉप रेटेड",
    upcoming: "आगामी",
    gptSearch: "जीपीटी खोज",
    searchLabel: "खोज",
    searchPlaceHolder: "आज आप क्या देखना चाहते हैं?",
    homePageLabel: "होम पेज",
    signInLabel: "साइन इन करें",
    signUpLabel: "साइनअप करें",
    newUser: "नेटफ्लिक्स पर नए हैं?",
    exisitingUser: "पहले से ही एक उपयोगकर्ता",
    signUpNow: "अभी साइनअप करें",
    namePlaceholder: "नाम",
    emailPlaceholder: "ईमेल",
    passwordPlaceholder: "पासवर्ड",
    signOutLabel: "साइन आउट",
  },
};

export const languageOption = [
  { title: "English", value: "en" },
  {
    title: "Hindi",
    value: "hindi",
  },
];
